version: 2.1

executors:
  unity_exec:
    docker:
      - image: unityci/editor:2020.3.22f1-linux-il2cpp-0.17.2
    environment:
      BUILD_NAME: blank-unity-project

.build: &build
  executor: unity_exec
  steps:
    - checkout
    - run: 
        name: Converting Unity license
        command: chmod +x ./ci/unity_license.sh && ./ci/unity_license.sh
    - run:
        name: Building game binaries
        command: chmod +x ./ci/build.sh && ./ci/build.sh
    - run: 
        name: Zipping build
        command: apt update && apt -y install zip && zip -r "build.zip" ./Builds/
    - store_artifacts:
        path: build.zip
jobs:
  build_android:
    <<: *build
    environment:
      BUILD_TARGET: Android
          
workflows:
  version: 2
  build:
    jobs:
      - build_android
